package com.example.demo;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller // This means that this class is a Controller
//@RequestMapping(path = "/") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	private CRepository cRepository;

	@GetMapping("/clientLogin") // 회원 로그인
	public String clientLogin() {
		return "clientLogin";
	}
	
	@GetMapping("/managerLogin") // 관리자 로그인
	public String managerLogin() {
		return "managerLogin";
	}

	@PostMapping("/clientLogin") //로그인
	public String getUser(Client ct) {

		List<Client> cl = cRepository.findByid(ct.getId());
		if (cl.isEmpty()) { // 아이디 없음
			return "/failClientLogin"; 
		}
		if (ct.getPassword().equals(cl.get(0).getPassword())) {
			// 로그인 성공
			return "";  //홈페이지 url
		}
		return "/failClientLogin";
	}
	
	@GetMapping("/menberjoin") // 회원가입
	public String menberjoin() {
		return "menberjoin";
	}
	
	@PostMapping("/menberjoin") //로그인
	public String menberjoinPost(Client ct) {
		cRepository.save(ct);
		return "failClientLogin";
	}
	
}